{% set name = "pscript" %}
{% set version = "0.6.1" %}
{% set sha256 = "05994f4e3aeb2bb40a450dae16d53fec3402f19ee9a3b31d0942169d2c8b504a" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
  number: 1

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - pscript

about:
  home: http://pscript.readthedocs.io
  doc_url: http://pscript.readthedocs.io
  dev_url: https://github.com/flexxui/pscript
  summary: library for transpiling Python code to JavaScript.
  license: BSD 2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - almarklein
