travis:
  secure:
    BINSTAR_TOKEN: zDAIkCcrpopmtmQrE8hss6jsIEp44MffUAtBvN/qngPcZkD8gwYiQf6FM68CK3G7G8Zs1tPGFgYalmic6HwVp1+qWc79FxfdtJez4jonFWKfKxcVO9x2baWyebS8KBQtmbCoB0l5rkafsCJfqx3C1Pz2vzNmM+kFHQLvOFYhDzbafzRNCAyvzV7FdQYQyTOic9lG8UwMM6T1iWSTtXrP4ooWfhP/0HLt8KxgIOYpCsMDH5uWkB63J8TmcoC5zfTjXWQLcT6Ifym2QJYpZyndSryKOKnZJ0gzCMbsgK4Gb91QC6seVtKw2YQlffNckpPMFcvTG39EKtnmEPoksDRYWfnNyAnTp9KJmnql2GpQWbo2NwPotNR3hSFHndwUxlW0lxecyKJ4EfgjtipMbnbrMoT7UF4sYxnUf62p1ovKDK0jsVH89EZOVLzoJu59l5RHcXYkMT8yWnpfamYbSR8BF7FsrF+pv4anz3Xxdu6KkUd8Hc9qhU7XLh/Mmtrlp1dHKCq5aidwVPYwHPtf7nM/TKlNiM+wKDZ5zG6l+ZgGyrmaKWv5coWJnEv4feGyR6FIS8KZTmx4eBaupj4TuFiUhBk0cjAdXP96sssI7IIoz5fm4BU/o83ZNU0HOcPwuxLbB/w7tsk6KsHoHIKCrXfX2h+wEWI0KOvIlVhcZg4co9g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
