travis:
  secure:
    BINSTAR_TOKEN: At+OHkJaG891lYUAZ5bzl6Hl59kYTlRDP43JWX+OE6wH+QaJCCkaqobNtS1IfL6SOftWBg9OaEsxsGMSwJUsJRqcrNQg1LDaCWS63ihemUZBu93EL/y4Z5hZglmnD82+hZOI0VJJB+drNfj/TPIWZYt0/w6x1JabtfRSrTuvB2HJzfcZJFH1h43kUoFPh9ZA15ql1OCndtWtKDp0nS5Jb/wE0nOwUWSV6UgCEcuatBQ4KHa1cioEK4nruWfOn4tuxEW6o6HRY15H2vfDgo1k/Wej+AJk/xUhLKjXb+0Qdtcz/R7aSOmVKpL3cgWcX1QVUV2PC9OA8wAU9M6goyvSLFrEMpWfPZIbZ7CJvG/fppbcCWUGvV98MiGpXhZ3UHR3gUiOZQmaTaT6WZGZn7gRsw4DP3TMIlJD9GqM70aqc0q2Va21z9S8e9tE6dMcQSV3a67VI3Ptsb8YxFpCpZvVmn4Jq1+5dqNE7Jv4ElH5iOJ3wg5kCe+j+oKWNTuCMYC9Ibzi6PTkfVSa0CcSrjcZ8JB2YJ8KXOdJp36xduMrfe7G9YjmBQqLInMZFio7rIBspGkMaxIIWa/09k919zCpLDZu2MmfBzyoHzZQo/GXpKtR0qnfz/+mDF52Irp/+9aPmS5fHRgWZMlPvwU2xv+huGDeeLJTIeDjsGjRBcM+Xr0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
