travis:
  secure:
    BINSTAR_TOKEN: I7bbN1/ll8h3+uiYDNOSzco+RPQsOV0n26/ovsFckYbokCgbbQJBoWoCFfmpsyKWV0DwY09p37ZQjKzP3DpgxlKfRoCRpbHeY/yn8tTWK7Yx4/APqtIcEZOgirQIMq06vf69eAo/h4tWwp8TnsLCgv8uPvZrjJ8sS6OQBnlAwgjGUQvL3aX9bwZR5qE8T3NVIn9g6HKpeCrxk2oGRknkaFuXwnxTFGIX08/vBjam+t5uPRgP6mvwlQqLGDq6t9pxHQcUZIonMROKygtIeoDdISxXotwg41YfDe+NaBvx+Es9R3IH/AVMRMS6NPxlJUVj4QaaXu2rDmDdmzvff+VztjsnYG6rfCe1H6HP0B6WGkNkk+I5Xycbzcg4MLx13hUNB/x/NXCAJDBflHCsToPju1e1znJ+bL5T3sOlwwXx0U2eEAQdwSHPx9I1uZUlkTTSOTUD7E3yF4QYusaz15JhgXHRnm+C5sxZtgfEawHjmYE/6AtsWyUZ1FCThq1ivBMPW0G+uakv8ZqaweoKMtz7f0rXQxG10u06V+fDJRmJy4NbeICbRxSFf+nRHFAwRa3wliiKcqfL6EGKy421e8OO41yWnTgcho6bN88xLjSCTKdT9L5atXLKRRHv3VeM2e9DgZua8F6ZA0p6GZU5IK+hyEzWHX/Ll1/Es1lA3MoZDQU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
