travis:
  secure:
    BINSTAR_TOKEN: xHs4tbdTCIoLgsA8Zy8j/hrsPWIU8UBQPLKHYoKsBAGsR4yju1uHS2qxPt+Z4krK8vl6eqilDE1l7yjniVT0pm4KIsH+QY0KzFBh0IhQjXEsXOA1hhVJWMzn/qA9RVh9kJ8IWKKFls1YwfgdtN9m3PJEtnpbrzhpHUYiu6b4RKqG5zma7ApSkAbUGUQFjy0i95lcmHY6Ab1d5W9y7R9Mc0Iw/ALPc2jmLg4ud3ZWtYUHxfMLqan+r7hpUqAbxrs6wl4NNhMFtcAwt/l4rDo6KlVdghVazyc0NUrdmD5mjQOKcE0vQut2VvqjDnEJrzaKf28radCfhPX0hYSYTXj6EbHkSrbsrG9HjJpuwiQCg6Ap1cPQFkfn/00W5zVPJGJVQ2JYF2unmOM2vAMpEoDXoFM9dM06MvlLc1p6KUM/gFcADAV5tw1KNRTETV1Ir9GUOMkQUSpFcUZWaVF5f1BzDxRNmAydIhVwgVKHF9/FLh8WeRIPqk+SWJ3ZBQhHB/o130IlyK4m5kXuLUNuqQ/QRneJoOTAYiN/H3nWN3+vSc29lKMrEYB/VvZu2xuEsiGqxJ8oB9NT9eOpU6Hq+Aw1i5jznx32VFvQl9j5aZi4ME08xPc6iUoDAHQddu+xg7gMSDIqXyVpKOq6uY7btkGrf8jvkXZP5/Yqa2YshXMWoXg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
